version: "3.7"
services:
  api_service:
    build: .
    restart: always
    environment:
      - PORT=8187
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
    depends_on:
      - postgres

  postgres:
    image: "postgres:13.3"
    restart: always
    ports:
      - 5437:5432
    environment:
     POSTGRES_USER: postgres
     POSTGRES_DB: postgres
     POSTGRES_PASSWORD: Ltnjxrf1
     POSTGRES_HOST_AUTH_METHOD: trust